language: generic
services:
  - docker
before_install:
  - docker-compose up -d --build
  - cp ./src/.env.example ./src/.env
  - docker-compose run --rm sudo composer install
  - docker-compose run --rm key:generate
  - docker-compose run --rm migrate:refresh --seed
  - docker-compose run --rm php ./vendor/bin/phpunit

