version: '3'

networks:
  volopa:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
        - NGINXUSER=${NGINXUSER:-www-data}
        - NGINXGROUP=${NGINXGROUP:-www-data}
    container_name: nginx_${NAME}
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks:
      volopa:
        aliases:
          - ${NAME}.localhost

  mysql:
    image: mariadb:10.6
    container_name: mysql_${NAME}
    restart: unless-stopped
    tty: true
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - volopa

  php:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - PHPUSER=${PHPUSER:-www-data}
        - PHPGROUP=${PHPGROUP:-www-data}
    container_name: php_${NAME}
    volumes:
      - ./src:/var/www/html:delegated
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - volopa

  redis:
    image: redis:alpine
    container_name: redis_${NAME}
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - volopa

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
      args:
        - PHPUSER=${PHPUSER:-www-data}
        - PHPGROUP=${PHPGROUP:-www-data}
    container_name: composer_${NAME}
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: ${PHPUSER:-www-data}
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - volopa

  npm:
    image: node:${NODE_VERSION}
    container_name: npm_${NAME}
    volumes:
      - ./src:/var/www/html
    ports:
      - ${NODE_PORT_1}:3000
      - ${NODE_PORT_2}:3001
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - volopa

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        - PHPUSER=${PHPUSER:-www-data}
        - PHPGROUP=${PHPGROUP:-www-data}
    container_name: artisan_${NAME}
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - volopa

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog_${NAME}
    ports:
      - ${MAILHOG_PORT_1}:1025
      - ${MAILHOG_PORT_2}:8025
    networks:
      - volopa
